#!/usr/bin/env sh

: ${SANDBOX_NAME:="sbx-0"}
: ${SANDBOX_NUMBER:="${SANDBOX_NAME##*-}"}
: ${SANDBOX_PATH:="/chroot/${SANDBOX_NAME}"}

setup_chroot() {
    mkdir -p \
        "${SANDBOX_PATH}/dev" \
        "${SANDBOX_PATH}/home" \
        "${SANDBOX_PATH}/tmp"

    chown nobody \
        "${SANDBOX_PATH}/home" \
        "${SANDBOX_PATH}/tmp"

    mknod -m 0666 "${SANDBOX_PATH}/dev/null" c 1 3
    mknod -m 0666 "${SANDBOX_PATH}/dev/urandom" c 1 9
}

setup_network() {
    set -ex

    DEVICE="mega${SANDBOX_NUMBER}"
    ADDRESS="$(ip addr show dev eth0 | awk '/inet/ {print $2}')"
    GATEWAY="$(ip route show dev eth0 | awk '/default/ {print $3}')"

    # Create a network namespace
    ip netns add "$SANDBOX_NAME"

    # Create a vlan device for the host
    ip link add "$DEVICE" link eth0 type macvlan mode bridge
    ip link set "$DEVICE" up
    ip addr add "10.0.${SANDBOX_NUMBER}.0/31" dev "$DEVICE"
    ip route add "10.0.${SANDBOX_NUMBER}.1" dev "$DEVICE"

    # Create a vlan device for the namespace
    ip link add vlan link eth0 type macvlan mode bridge
    ip link set vlan netns "$SANDBOX_NAME"
    ip netns exec "$SANDBOX_NAME" ip link set vlan name eth0
    ip netns exec "$SANDBOX_NAME" ip link set eth0 up
    ip netns exec "$SANDBOX_NAME" ip link set lo up
    ip netns exec "$SANDBOX_NAME" ip addr add "10.0.${SANDBOX_NUMBER}.1" dev eth0
    ip netns exec "$SANDBOX_NAME" ip route add "10.0.${SANDBOX_NUMBER}.0/31" dev eth0
    ip netns exec "$SANDBOX_NAME" ip addr add "$ADDRESS" dev eth0
    ip netns exec "$SANDBOX_NAME" ip route add default via "$GATEWAY" dev eth0

    # Set up routing tables
    ip netns exec "$SANDBOX_NAME" /usr/sbin/nft -f /etc/nftables.d/docker.nft
    nft add rule inet filter input oifname "$DEVICE" accept
    nft add rule inet filter output iifname "$DEVICE" accept
}

sandbox() {
    CMD="$@"

    ip netns exec ${SANDBOX_NAME} su -s /bin/sh -c " \
        export HOME=/home
        unshare -r \
        chroot ${SANDBOX_PATH} \
        ${CMD}
    " nobody
}

if type "$1" | grep -q "function"; then "$1"; else sandbox "$@"; fi
